version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/api
      - bundle:/bundle
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  bundle:
  mysql-data:
    driver: local
